### ISSUE TITLE
Unable to run on server

### ISSUE THREAD

**Issue by d6u** [fcomb/redux-logger#120]
I know it doesn't make sense to run on server, but it's very convenient for server rendering.

I'm using 2.4.0.

```
/Users/daiwei/dev/projects/github-starboard/node_modules/redux-logger/lib/index.js:39
  var logger = _options$logger === undefined ? window.console : _options$logger;
                                               ^
ReferenceError: window is not defined
    at createLogger (/Users/daiwei/dev/projects/github-starboard/node_modules/redux-logger/lib/index.js:39:48)
    at Object.<anonymous> (/Users/daiwei/dev/projects/github-starboard/source/universal/store.js:13:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/daiwei/dev/projects/github-starboard/source/server/routers/util/renderReact.js:29:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/daiwei/dev/projects/github-starboard/source-node5/server/routers/html/public.js:12:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/daiwei/dev/projects/github-starboard/source-node5/server/routers/html/index.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

I confirmed this is not an issue in 2.3.2.

**Comment by edorivai** [comment]
You could specify `logger: console`:

```JS
createLogger({ logger: console })`
```

**Comment by theaqua** [comment]
@edorivai is right.

**Comment by d6u** [comment]
Thanks
